### ISSUE TITLE
コードベースからの日本語排除

### ISSUE THREAD

**Issue by geckour** [ysk1025/AnycaToCalendar#1]
漢字・ひらがな・カタカナなど表記ゆれから一意性を担保しづらくなるので

- ファイル名
- コード内のコメントや文字列定数など影響範囲の少ないもしくは必要である部分以外

からの日本語を排除したほうが良いのではないか

**Comment by ysk1025** [comment]
初issueをありがとう。
ひとまずフィル名から日本語を排除しました。
プログラミングをよく知らない人が触る前提があるので、コード内はこのままいく方針です。
